branches:
  only:
    - staging
    - master
    - trying

language: java

jdk: oraclejdk8

env:
  - RUST_VERSION=nightly ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
  - RUST_VERSION=stable
  - RUST_VERSION=1.18.0  ORG_GRADLE_PROJECT_ideaVersion=2017.2.5

matrix:
  fast_finish: true
  allow_failures:
    - env: RUST_VERSION=nightly ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT

install: true

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustfmt --help || cargo install rustfmt --force
  - ./check-license.sh
  - ./gradlew :resolveDependencies -Pkotlin.incremental=false --no-daemon
  - ./gradlew assemble testClasses -Pkotlin.incremental=false --no-daemon

script:
  - ./gradlew check -Pkotlin.incremental=false --no-daemon

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cargo/registry/cache/
    - $HOME/.cargo/registry/src/
    - $HOME/.cargo/bin/
